### ISSUE TITLE
Logging doesn't show up on the console

### ISSUE THREAD

**Issue by MichielTukker** [Project-OMOTES/simulator-worker#1]
Python logging doesn't show in the console.  issue with logging handlers not being initialized correctly? 

Is this issue also with optimizer-worker?

**Comment by lfse-slafleur** [comment]
Should be fixed with https://github.com/Project-OMOTES/simulator-worker/issues/17. Optimizer was sort of working as a spurrious logging handler printed something to console but it wasn't working fully and controlled either. But because it showed some output, the issue wasn't pronounced. Closing as the other issue with PR will fix it.
